#pragma once

#define IDR_DEFAULT_RULESET 101

#define IDD_PREPARE_TRACKS 200
#define IDC_PREPARE_PROFILE 201
#define IDC_PREPARE_NAME 202
#define IDC_PREPARE_DESTINATION 203
#define IDC_PREPARE_PATTERN 204

#define IDD_MENU_PREFERENCES 230
#define IDC_CAPTION_METADATA 231
#define IDC_CAPTION_SINGLES 232
#define IDC_CAPTION_ALBEN 233
#define IDC_CAPTION_LIVESETS 234
#define IDC_CAPTION_PREPARE 235
