#pragma once

#define IDR_DEFAULT_RULESET 101

#define IDD_PREPARE_TRACKS 200
#define IDC_PREPARE_PROFILE 201
#define IDC_PREPARE_NAME 202
#define IDC_PREPARE_DESTINATION 203
#define IDC_PREPARE_PATTERN 204

#define IDD_MENU_PREFERENCES 230
#define IDC_CAPTION_METADATA 231
#define IDC_CAPTION_SINGLES 232
#define IDC_CAPTION_ALBEN 233
#define IDC_CAPTION_LIVESETS 234
#define IDC_CAPTION_PREPARE 235

#define IDD_BATCH_PREVIEW 260
#define IDC_BATCH_LIST 261
#define IDC_BATCH_PROFILE_PICKER 262
#define IDC_BATCH_PROFILE_NAME 263
#define IDC_BATCH_DESTINATION 264
#define IDC_BATCH_PATTERN 265
#define IDC_BATCH_APPLY_SELECTED 266
#define IDC_BATCH_APPLY_ALL 267

#define IDC_BATCH_TABS 270
#define IDC_METADATA_LIST 271
#define IDC_BATCH_HINT 272

#define IDC_METADATA_TRACK_LIST 273
#define IDC_METADATA_FILTER 274
#define IDC_METADATA_FILTER_LABEL 275

#define IDC_BATCH_ROUTE_LABEL 276
#define IDC_BATCH_NAME_LABEL 277
#define IDC_BATCH_DEST_LABEL 278
#define IDC_BATCH_PATTERN_LABEL 279

#define IDC_METADATA_TRACK_FILTER 280
#define IDC_METADATA_TRACK_FILTER_LABEL 281
