#pragma once

#define IDR_DEFAULT_RULESET 101

#define IDD_PREPARE_TRACKS 200
#define IDC_PREPARE_PROFILE 201
#define IDC_PREPARE_NAME 202
#define IDC_PREPARE_DESTINATION 203
#define IDC_PREPARE_PATTERN 204
